CREATE TABLE IF NOT EXISTS MEAL
(
    id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    name VARCHAR     NOT NULL,
    type VARCHAR(10) NOT NULL check (type in ('BREAKFAST', 'LUNCH', 'DINNER'))
);

